# Generated by Django 5.0.4 on 2024-05-22 07:42

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default='', max_length=25)),
                ('number', models.IntegerField()),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.IntegerField()),
                ('date', models.DateField(default=datetime.datetime(2024, 5, 22, 13, 12, 46, 262734))),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.product')),
                ('register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.register')),
            ],
        ),
    ]
